export const SUBJECTS_LIST = [
  { "id": "history", "name": "History" },
  { "id": "culture", "name": "Indian Culture" },
  { "id": "geography", "name": "Geography" },
  { "id": "environment", "name": "Ecology & Environment" },
  { "id": "polity", "name": "Indian Polity & Governance" },
  { "id": "economy", "name": "Economy" },
  { "id": "science_tech", "name": "Science & Technology" },
  { "id": "general_science", "name": "General Science" }
];

export const CHAPTERS_LIST = [
  { "id": "ancient_history", "name": "Ancient History", "subjectId": "history" },
  { "id": "medieval_history", "name": "Medieval History", "subjectId": "history" },
  { "id": "modern_history", "name": "Modern History", "subjectId": "history" },

  { "id": "visual_arts", "name": "Visual Arts", "subjectId": "culture" },
  { "id": "performing_arts", "name": "Performing Arts", "subjectId": "culture" },
  { "id": "religion_literature", "name": "Religion, Language and Literature", "subjectId": "culture" },
  { "id": "culture_misc", "name": "Miscellaneous", "subjectId": "culture" },

  { "id": "general_geography", "name": "General Geography", "subjectId": "geography" },
  { "id": "geomorphology", "name": "Geomorphology", "subjectId": "geography" },
  { "id": "oceanography", "name": "Oceanography", "subjectId": "geography" },
  { "id": "climatology", "name": "Climatology", "subjectId": "geography" },
  { "id": "bio_geography", "name": "Bio-Geography", "subjectId": "geography" },
  { "id": "human_geo", "name": "Human & Economic Geography", "subjectId": "geography" },
  { "id": "indian_geo", "name": "Indian Geography", "subjectId": "geography" },
  { "id": "world_geo", "name": "World Regional Geography", "subjectId": "geography" },

  { "id": "ecology", "name": "Environmental Ecology", "subjectId": "environment" },
  { "id": "biodiversity", "name": "Biodiversity", "subjectId": "environment" },
  { "id": "resource_management", "name": "Resource Degradation & Management", "subjectId": "environment" },
  { "id": "pollution", "name": "Environmental Pollution", "subjectId": "environment" },
  { "id": "climate_change", "name": "Climate Change", "subjectId": "environment" },
  { "id": "env_governance", "name": "Environmental Governance", "subjectId": "environment" },

  { "id": "constitution", "name": "Constitution", "subjectId": "polity" },
  { "id": "rights", "name": "Rights & Duties", "subjectId": "polity" },
  { "id": "governance", "name": "Governance", "subjectId": "polity" },
  { "id": "bodies", "name": "Bodies", "subjectId": "polity" },
  { "id": "international_relations", "name": "International Relations", "subjectId": "polity" },

  { "id": "economy_basics", "name": "Basic Concepts", "subjectId": "economy" },
  { "id": "economic_measurement", "name": "Economic Measurements", "subjectId": "economy" },
  { "id": "money_banking", "name": "Money & Banking", "subjectId": "economy" },
  { "id": "public_finance", "name": "Public Finance", "subjectId": "economy" },
  { "id": "planning", "name": "Planning", "subjectId": "economy" },
  { "id": "open_economy", "name": "Open Economy", "subjectId": "economy" },
  { "id": "economic_sectors", "name": "Economic Sectors", "subjectId": "economy" },

  { "id": "science_dev", "name": "Science & Technology in India", "subjectId": "science_tech" },
  { "id": "space", "name": "Space", "subjectId": "science_tech" },
  { "id": "it", "name": "IT & Communication", "subjectId": "science_tech" },
  { "id": "nano_robotics", "name": "Materials, Nano Tech & Robotics", "subjectId": "science_tech" },
  { "id": "defence", "name": "Defence", "subjectId": "science_tech" },
  { "id": "nuclear", "name": "Nuclear Technology", "subjectId": "science_tech" },
  { "id": "ipr", "name": "IPR & Misc", "subjectId": "science_tech" },
  { "id": "biotech", "name": "Biotechnology", "subjectId": "science_tech" },

  { "id": "biology", "name": "Biology", "subjectId": "general_science" }
];

export const SUBTOPICS_LIST = [
  // ---------------- HISTORY ----------------
  { "id": "prehistoric_times", "name": "Pre Historic Times", "chapterId": "ancient_history" },
  { "id": "indus_valley", "name": "Indus Valley Civilization", "chapterId": "ancient_history" },
  { "id": "rig_vedic", "name": "Rig Vedic Period", "chapterId": "ancient_history" },
  { "id": "later_vedic", "name": "Later Vedic Period", "chapterId": "ancient_history" },
  { "id": "jainism", "name": "Jainism", "chapterId": "ancient_history" },
  { "id": "buddhism", "name": "Buddhism", "chapterId": "ancient_history" },
  { "id": "mahajanapadas", "name": "Mahajanapadas Period", "chapterId": "ancient_history" },
  { "id": "mauryan_empire", "name": "Mauryan Empire", "chapterId": "ancient_history" },
  { "id": "post_mauryan", "name": "Post Mauryan India", "chapterId": "ancient_history" },
  { "id": "gupta_period", "name": "Gupta Period", "chapterId": "ancient_history" },
  { "id": "harsha", "name": "Harshavardhana Period", "chapterId": "ancient_history" },
  { "id": "sangam", "name": "Sangam Period", "chapterId": "ancient_history" },

  { "id": "early_medieval_dynasties", "name": "Early Medieval Dynasties", "chapterId": "medieval_history" },
  { "id": "cholas_south", "name": "Cholas and South Indian Kingdoms", "chapterId": "medieval_history" },
  { "id": "early_muslim_invasions", "name": "Early Muslim Invasions", "chapterId": "medieval_history" },
  { "id": "delhi_sultanate", "name": "Delhi Sultanate", "chapterId": "medieval_history" },
  { "id": "mughal_struggle", "name": "Struggle for Empire in North India", "chapterId": "medieval_history" },
  { "id": "mughal_establishment", "name": "Establishment of Mughal Empire", "chapterId": "medieval_history" },
  { "id": "akbar_expansion", "name": "Akbar Expansion", "chapterId": "medieval_history" },
  { "id": "akbar_governance", "name": "State and Government under Akbar", "chapterId": "medieval_history" },
  { "id": "akbar_religion", "name": "Akbar Religious Policy", "chapterId": "medieval_history" },
  { "id": "deccan_mughals", "name": "Deccan and Mughals", "chapterId": "medieval_history" },
  { "id": "mughal_foreign_policy", "name": "Mughal Foreign Policy", "chapterId": "medieval_history" },
  { "id": "mughal_society", "name": "Mughal Society", "chapterId": "medieval_history" },
  { "id": "marathas", "name": "Marathas and Deccan", "chapterId": "medieval_history" },
  { "id": "regional_states", "name": "Regional States", "chapterId": "medieval_history" },

  { "id": "advent_europeans", "name": "Advent of Europeans", "chapterId": "modern_history" },
  { "id": "british_expansion", "name": "British Expansion", "chapterId": "modern_history" },
  { "id": "admin_before_1857", "name": "Administration before 1857", "chapterId": "modern_history" },
  { "id": "economic_policies", "name": "Economic Policies of British", "chapterId": "modern_history" },
  { "id": "impact_british", "name": "Impact of British Rule", "chapterId": "modern_history" },
  { "id": "revolt_1857", "name": "Revolt of 1857", "chapterId": "modern_history" },
  { "id": "post_1857_changes", "name": "Administrative Changes after 1857", "chapterId": "modern_history" },
  { "id": "civil_services", "name": "Development of Civil Services", "chapterId": "modern_history" },
  { "id": "education", "name": "Development of Education", "chapterId": "modern_history" },
  { "id": "press", "name": "Development of Press", "chapterId": "modern_history" },
  { "id": "socio_reforms", "name": "Socio Religious Reforms", "chapterId": "modern_history" },
  { "id": "personalities", "name": "Important Personalities", "chapterId": "modern_history" },
  { "id": "movements", "name": "Peasant and Tribal Movements", "chapterId": "modern_history" },
  { "id": "revolutionary", "name": "Revolutionary Nationalism", "chapterId": "modern_history" },
  { "id": "national_movement_1", "name": "National Movement Phase 1", "chapterId": "modern_history" },
  { "id": "national_movement_2", "name": "National Movement Phase 2", "chapterId": "modern_history" },
  { "id": "national_movement_3", "name": "National Movement Phase 3", "chapterId": "modern_history" },
  { "id": "governor_generals", "name": "Governor Generals", "chapterId": "modern_history" },
  { "id": "constitutional_dev", "name": "Constitutional Development", "chapterId": "modern_history" },

  // ---------------- CULTURE ----------------
  { "id": "architecture", "name": "Architecture", "chapterId": "visual_arts" },
  { "id": "sculpture", "name": "Sculptures", "chapterId": "visual_arts" },
  { "id": "paintings", "name": "Paintings", "chapterId": "visual_arts" },
  { "id": "pottery", "name": "Pottery Tradition", "chapterId": "visual_arts" },
  { "id": "numismatics", "name": "Numismatics", "chapterId": "visual_arts" },

  { "id": "music", "name": "Music in India", "chapterId": "performing_arts" },
  { "id": "dance", "name": "Dance in India", "chapterId": "performing_arts" },
  { "id": "sports", "name": "Sports in India", "chapterId": "performing_arts" },
  { "id": "theatre", "name": "Indian Theatre", "chapterId": "performing_arts" },
  { "id": "puppetry", "name": "Indian Puppetry", "chapterId": "performing_arts" },

  { "id": "religions", "name": "Religions in India", "chapterId": "religion_literature" },
  { "id": "languages", "name": "Languages and Literature", "chapterId": "religion_literature" },

  // ---------------- GEOGRAPHY ----------------
  { "id": "earth_structure", "name": "Earth Interior", "chapterId": "general_geography" },
  { "id": "universe", "name": "Universe", "chapterId": "general_geography" },
  { "id": "earth_evolution", "name": "Earth Evolution", "chapterId": "general_geography" },

  { "id": "rocks", "name": "Rocks and Minerals", "chapterId": "geomorphology" },
  { "id": "geomorphic_processes", "name": "Geomorphic Processes", "chapterId": "geomorphology" },
  { "id": "earthquakes", "name": "Earthquakes", "chapterId": "geomorphology" },
  { "id": "volcanism", "name": "Volcanism", "chapterId": "geomorphology" },
  { "id": "plate_tectonics", "name": "Plate Tectonics", "chapterId": "geomorphology" },
  { "id": "landforms", "name": "Landforms", "chapterId": "geomorphology" },
  { "id": "weathering", "name": "Weathering", "chapterId": "geomorphology" },

  { "id": "hydrosphere", "name": "Hydrosphere", "chapterId": "oceanography" },
  { "id": "ocean_relief", "name": "Ocean Relief", "chapterId": "oceanography" },
  { "id": "ocean_currents", "name": "Ocean Currents", "chapterId": "oceanography" },

  { "id": "atmosphere", "name": "Atmosphere", "chapterId": "climatology" },
  { "id": "temperature", "name": "Temperature", "chapterId": "climatology" },
  { "id": "winds", "name": "Winds and Pressure Belts", "chapterId": "climatology" },
  { "id": "cyclones", "name": "Cyclones", "chapterId": "climatology" },
  { "id": "precipitation", "name": "Precipitation", "chapterId": "climatology" },

  { "id": "soils", "name": "Soil", "chapterId": "bio_geography" },
  { "id": "vegetation", "name": "Vegetation", "chapterId": "bio_geography" },

  { "id": "population", "name": "Population", "chapterId": "human_geo" },
  { "id": "human_dev", "name": "Human Development", "chapterId": "human_geo" },
  { "id": "economic_activities", "name": "Economic Activities", "chapterId": "human_geo" },
  { "id": "physical_features_india", "name": "Physical Features", "chapterId": "indian_geo" },
  { "id": "climate_india", "name": "Climate of India", "chapterId": "indian_geo" },
  { "id": "drainage_system", "name": "Drainage System", "chapterId": "indian_geo" },
  { "id": "continents", "name": "Continents", "chapterId": "world_geo" },
  { "id": "world_resources", "name": "Resources of the World", "chapterId": "world_geo" },

  // ---------------- ENVIRONMENT ----------------
  { "id": "ecology", "name": "Environmental Ecology", "chapterId": "ecology" },
  { "id": "biodiversity", "name": "Biodiversity", "chapterId": "biodiversity" },
  { "id": "pollution", "name": "Pollution", "chapterId": "pollution" },
  { "id": "climate_change", "name": "Climate Change", "chapterId": "climate_change" },

  // ---------------- POLITY ----------------
  { "id": "constitution", "name": "Constitution Basics", "chapterId": "constitution" },
  { "id": "citizenship", "name": "Citizenship", "chapterId": "constitution" },
  { "id": "fundamental_rights", "name": "Fundamental Rights", "chapterId": "rights" },
  { "id": "dpsp", "name": "Directive Principles", "chapterId": "rights" },
  { "id": "parliament", "name": "Parliament", "chapterId": "governance" },
  { "id": "judiciary", "name": "Judiciary", "chapterId": "governance" },
  { "id": "executive", "name": "Executive", "chapterId": "governance" },
  { "id": "local_gov", "name": "Local Government", "chapterId": "governance" },
  { "id": "elections", "name": "Elections", "chapterId": "governance" },
  { "id": "constitutional_bodies", "name": "Constitutional Bodies", "chapterId": "bodies" },
  { "id": "statutory_bodies", "name": "Statutory Bodies", "chapterId": "bodies" },
  { "id": "foreign_policy", "name": "Foreign Policy", "chapterId": "international_relations" },
  { "id": "international_orgs", "name": "International Organizations", "chapterId": "international_relations" },

  // ---------------- ECONOMY ----------------
  { "id": "basic_concepts", "name": "Basic Concepts", "chapterId": "economy_basics" },
  { "id": "gdp", "name": "GDP", "chapterId": "economic_measurement" },
  { "id": "money_banking", "name": "Money and Banking", "chapterId": "money_banking" },
  { "id": "budget", "name": "Budget", "chapterId": "public_finance" },
  { "id": "fiscal_policy", "name": "Fiscal Policy", "chapterId": "public_finance" },
  { "id": "five_year_plans", "name": "Five Year Plans", "chapterId": "planning" },
  { "id": "niti_aayog", "name": "NITI Aayog", "chapterId": "planning" },
  { "id": "foreign_trade", "name": "Foreign Trade", "chapterId": "open_economy" },
  { "id": "fdi", "name": "FDI and FII", "chapterId": "open_economy" },
  { "id": "agriculture", "name": "Agriculture", "chapterId": "economic_sectors" },
  { "id": "industry", "name": "Industry", "chapterId": "economic_sectors" },
  { "id": "services", "name": "Services Sector", "chapterId": "economic_sectors" },

  // ---------------- SCIENCE ----------------
  { "id": "science_dev_india", "name": "Science and Tech in India", "chapterId": "science_dev" },
  { "id": "space", "name": "Space Technology", "chapterId": "space" },
  { "id": "biotech", "name": "Biotechnology", "chapterId": "biotech" },
  { "id": "it_communication", "name": "IT & Communication", "chapterId": "it" },
  { "id": "nano_tech", "name": "Nano Technology", "chapterId": "nano_robotics" },
  { "id": "robotics", "name": "Robotics", "chapterId": "nano_robotics" },
  { "id": "defence_tech", "name": "Defence Technology", "chapterId": "defence" },
  { "id": "nuclear_tech", "name": "Nuclear Technology", "chapterId": "nuclear" },
  { "id": "ipr_rights", "name": "Intellectual Property Rights", "chapterId": "ipr" },

  // ---------------- BIOLOGY ----------------
  { "id": "cell_biology", "name": "Origin of Life and Cells", "chapterId": "biology" },
  { "id": "genetics", "name": "Genetics", "chapterId": "biology" },
  { "id": "classification", "name": "Classification of Living Things", "chapterId": "biology" },
  { "id": "evolution", "name": "Evolution of Life", "chapterId": "biology" },
  { "id": "tissues", "name": "Tissues", "chapterId": "biology" },
  { "id": "endocrine", "name": "Endocrine System", "chapterId": "biology" },
  { "id": "respiratory", "name": "Respiratory System", "chapterId": "biology" },
  { "id": "transport", "name": "Transport System", "chapterId": "biology" },
  { "id": "skeletal", "name": "Skeletal System", "chapterId": "biology" },
  { "id": "reproduction", "name": "Reproductive System", "chapterId": "biology" },
  { "id": "excretory", "name": "Excretory System", "chapterId": "biology" },
  { "id": "nutrition", "name": "Nutrition", "chapterId": "biology" },
  { "id": "diseases", "name": "Diseases", "chapterId": "biology" },
  { "id": "economic_zoology", "name": "Economic Zoology", "chapterId": "biology" },
  { "id": "recent_bio", "name": "Recent Developments", "chapterId": "biology" }
];
